### ISSUE TITLE
Arrays not supported

### ISSUE THREAD

**Issue by sbinq** [mitchellh/reflectwalk#16]
Seems like arrays are currently not supported - test demonstrating this:

```
package main

import (
	"reflect"
	"testing"

	"github.com/mitchellh/reflectwalk"
	"github.com/stretchr/testify/require"
)

func TestWalksArray(t *testing.T) {
	type Nested struct {
		Field string
	}

	type Struct struct {
		Array [2]Nested
	}

	err := reflectwalk.Walk(Struct{}, walker{})
	require.Nil(t, err)
}

type walker struct{}

func (walker) Struct(reflect.Value) error {
	return nil
}

func (walker) StructField(reflect.StructField, reflect.Value) error {
	return nil
}
```

Output:
```
=== RUN   TestWalksArray
--- FAIL: TestWalksArray (0.00s)
panic: unsupported type: array [recovered]
	panic: unsupported type: array

goroutine 5 [running]:
panic(0x625800, 0xc420013570)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
testing.tRunner.func1(0xc420090180)
	/usr/local/go/src/testing/testing.go:579 +0x25d
panic(0x625800, 0xc420013570)
	/usr/local/go/src/runtime/panic.go:458 +0x243
github.com/mitchellh/reflectwalk.walk(0x629ca0, 0xc4200d6cc0, 0x91, 0x642bc0, 0x7b9888, 0x0, 0x0)
	/home/sbinq/work/gopath/vendor/src/github.com/mitchellh/reflectwalk/reflectwalk.go:183 +0x3a6
github.com/mitchellh/reflectwalk.walkStruct(0x640f40, 0xc4200d6cc0, 0x99, 0x642bc0, 0x7b9888, 0x101, 0x7bcf40)
	/home/sbinq/work/gopath/vendor/src/github.com/mitchellh/reflectwalk/reflectwalk.go:324 +0x3ad
github.com/mitchellh/reflectwalk.walk(0x640f40, 0xc4200d6cc0, 0x99, 0x642bc0, 0x7b9888, 0x0, 0x0)
	/home/sbinq/work/gopath/vendor/src/github.com/mitchellh/reflectwalk/reflectwalk.go:180 +0x4b2
github.com/mitchellh/reflectwalk.Walk(0x640f40, 0xc4200d6cc0, 0x642bc0, 0x7b9888, 0x7b9888, 0xc42002ff58)
	/home/sbinq/work/gopath/vendor/src/github.com/mitchellh/reflectwalk/reflectwalk.go:84 +0x155
_/home/sbinq/work/gopath/src.TestWalksArray(0xc420090180)
	/home/sbinq/work/gopath/src/sample_test.go:20 +0xcb
testing.tRunner(0xc420090180, 0x69e5f8)
	/usr/local/go/src/testing/testing.go:610 +0x81
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:646 +0x2ec
exit status 2
FAIL	_/home/sbinq/work/gopath/src	0.005s
```

**Comment by sbinq** [comment]
@mitchellh could you please review my pull request for this issue?

I suppose existing clients would not be affected, one note about compatibility though - adding `Array` and `ArrayElem` enumeration values in the _middle_ of `Location` enum actually changes binary values of subsequent constant values - I doubt this would be critical for anyone, but if you prefer to save compatibility about it - please let me know and I'll change the PR.

**Comment by mitchellh** [comment]
Thanks, that looks good. 

No worries adding values in the middle. People shouldn't be depending on the exact values of the enum since I don't see any utility in storing it.
